const INFINITY = 9999999
const WIDTH_SIZE = 500
const HEIGHT_SIZE = 500
const SCALE = 100
const dt = 0.1
const SPACIAL_MAGNIFICATION = 100
const CALCULATE_TIME_SCALE = 100
const FRAME_RATE = 10


const ORIGIN_X = WIDTH_SIZE / 2
const ORIGIN_Y = HEIGHT_SIZE / 2
const ORIGIN_VERTEX = new Vertex(ORIGIN_X, ORIGIN_Y)
const TOTAL_TIMESTEP_NUM = CALCULATE_TIME_SCALE / dt;
const DRAWING_TIME = 10;
const PLAYBACK_SPEED = CALCULATE_TIME_SCALE / DRAWING_TIME;